name: container
on: push

 
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: salestrip/sfdx-cli:latest
    steps:
         - name: Log the node version
           run: |
             sfdx --version
             node -v
             cat /etc/os-release  

         - name: Install power kit
           id : powerkit
           run : echo 'y' | sfdx plugins:install sfpowerkit

         - name: sfdx
           run : sfdx --version


# Allows you to run this workflow manually from the Actions tab

