name: container
on: push

 
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: salestrip/sfdx-cli:latest
    steps:
         - name: Log the node version
           run: |
             sfdx --version
             node -v
             cat /etc/os-release  

# Allows you to run this workflow manually from the Actions tab

